version: "3.8"

services:
  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    ports:
      - "7474:7474" # Neo4j browser
      - "7687:7687" # Bolt protocol
    volumes:
      - neo4j_data:/data
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_logs:/logs

  springboot-app:
    build: .
    environment:
      NEO4J_URI: ${NEO4J_URI:-bolt://neo4j:7687}
      NEO4J_USERNAME: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - neo4j

volumes:
  neo4j_data:
  neo4j_import:
  neo4j_logs:
